package org.example.quiz.model;

import java.sql.Timestamp;

public class Announcement {

    private long id;
    private String title;
    private String message;
    private long authorID;
    private boolean active;
    private Timestamp createdAt;  // generated by SQL but still needed here to read it back

    public Announcement(String title, String message, long authorID, boolean active) {
        this.title = title;
        this.message = message;
        this.authorID = authorID;
        this.active = active;
    }

    //setter and getter for the announcement's own id
    public long getId() {
        return id;
    }
    public void setId(long id) {
        this.id = id;
    }

    //setter and getter for the title
    public String getTitle() {
        return title;
    }
    public void setTitle(String title) {
        this.title = title;
    }

    //setter and getter for the message
    public String getMessage() {
        return message;
    }
    public void setMessage(String message) {
        this.message = message;
    }

    //setter and getter for the admin who posted this
    public long getAuthorID() {
        return authorID;
    }
    public void setAuthorID(long authorID) {
        this.authorID = authorID;
    }

    //setter and getter for the active state of this announcement
    public boolean isActive() {
        return active;
    }
    public void setActive(boolean active) {
        this.active = active;
    }

    //setter and getter for when this announcement was created
    public Timestamp getCreatedAt() {
        return createdAt;
    }
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }
}

